
export interface Recipe {
  id: string;
  name: string;
  ingredients: string[];
  steps: string[];
  image?: string;
  prepTime?: string;
  servings?: string;
  category: 
    | 'breakfast'
    | 'lunch-dinner'
    | 'snacks'
    | 'beverages'
    | 'desserts'
    | 'salads'
    | 'soups'
    | 'rice-dishes'
    | 'pasta-noodles'
    | 'bread-roti'
    | 'chinese'
    | 'italian'
    | 'mexican'
    | 'healthy'
    | 'street-food'
    | 'south-indian'
    | 'north-indian'
    | 'quick-meals'
    | 'biryani'
    | 'fried-rice'
    | 'pickles'
    | 'shakes'
    | 'detox-water'
    | 'curries'
    | 'non-veg-curries'
    | 'juices'
    | 'desserts-sweets'
    | 'roti-paratha'
    | 'ice-creams'
    | 'lunch-box'
    | 'party-starters'
    | 'one-pot-meals'
    | 'stir-fry'
    | 'sandwiches-wraps'
    | 'kids-special'
    | 'festive-specials'
    | 'beverages-mocktails'
    | 'tandoori'
    | 'rice-varieties'
    | 'dips-chutneys'
    | 'healthy-low-cal'
    | 'gravy-dishes'
    | 'baking-cakes'
    | 'quick-easy'
    | 'other';
}
